// Lightweight PDF generation using browser print API
// Generates a styled HTML document and triggers print/save as PDF

interface PDFSection {
  title: string;
  items: { label: string; value: string; color?: string }[];
  total?: { label: string; value: string; color?: string };
}

interface PDFOptions {
  title: string;
  subtitle?: string;
  date?: string;
  sections: PDFSection[];
  footer?: { label: string; value: string }[];
}

export function exportReportAsPDF(options: PDFOptions) {
  const { title, subtitle, date, sections, footer } = options;
  const reportDate = date || new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });

  const sectionsHTML = sections.map(s => `
    <div class="section">
      <h3>${s.title}</h3>
      ${s.items.map(item => `
        <div class="row">
          <span>${item.label}</span>
          <span style="color: ${item.color || '#1a1a1a'}; font-weight: 500;">${item.value}</span>
        </div>
      `).join("")}
      ${s.total ? `
        <div class="total-row" style="border-color: ${s.total.color || '#6366f1'}20; background: ${s.total.color || '#6366f1'}08;">
          <span style="font-weight: 700;">${s.total.label}</span>
          <span style="font-weight: 700; color: ${s.total.color || '#1a1a1a'};">${s.total.value}</span>
        </div>
      ` : ""}
    </div>
  `).join("");

  const footerHTML = footer ? `
    <div class="footer-section">
      ${footer.map(f => `
        <div class="footer-item">
          <span class="footer-label">${f.label}</span>
          <span class="footer-value">${f.value}</span>
        </div>
      `).join("")}
    </div>
  ` : "";

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #1a1a1a; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { border-bottom: 2px solid #6366f1; padding-bottom: 16px; margin-bottom: 32px; }
    .header h1 { font-size: 22px; font-weight: 700; color: #1a1a1a; }
    .header h2 { font-size: 14px; font-weight: 400; color: #6b7280; margin-top: 4px; }
    .header .company { font-size: 12px; color: #6366f1; font-weight: 600; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 4px; }
    .header .date { font-size: 12px; color: #9ca3af; margin-top: 4px; }
    .sections { display: grid; grid-template-columns: ${sections.length <= 2 ? 'repeat(2, 1fr)' : 'repeat(3, 1fr)'}; gap: 24px; }
    .section h3 { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 1.5px; color: #6b7280; margin-bottom: 12px; }
    .row { display: flex; justify-content: space-between; padding: 6px 12px; font-size: 13px; border-radius: 4px; }
    .row:hover { background: #f9fafb; }
    .total-row { display: flex; justify-content: space-between; padding: 10px 12px; font-size: 14px; border-radius: 6px; margin-top: 14px; border: 1px solid; }
    .footer-section { margin-top: 32px; padding: 20px; background: #f8f7ff; border-radius: 8px; border: 1px solid #e5e4ff; display: flex; justify-content: space-around; }
    .footer-item { text-align: center; }
    .footer-label { display: block; font-size: 11px; color: #6b7280; margin-bottom: 4px; }
    .footer-value { display: block; font-size: 20px; font-weight: 700; color: #1a1a1a; }
    .watermark { text-align: center; margin-top: 40px; font-size: 10px; color: #d1d5db; }
    @media print {
      body { padding: 20px; }
      .row:hover { background: transparent; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">GRX10 ERP</div>
    <h1>${title}</h1>
    ${subtitle ? `<h2>${subtitle}</h2>` : ""}
    <div class="date">As of ${reportDate}</div>
  </div>
  <div class="sections">${sectionsHTML}</div>
  ${footerHTML}
  <div class="watermark">Generated by GRX10 ERP &bull; ${reportDate}</div>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
    // Close the print window after printing (or cancelling)
    printWindow.onafterprint = () => {
      printWindow.close();
    };
    // Fallback: close after a short delay for browsers that don't support onafterprint
    setTimeout(() => {
      if (!printWindow.closed) {
        printWindow.close();
      }
    }, 1000);
  };
}
